// nodejs-tools/nodejs-apps/vighnesh153-astro/src/components/projects/drawing-app/DrawingAppRoot.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  import {
    type EventMode,
    Color,
    type IColor,
    BrushThickness,
    undo,
    redo,
    publishEvents,
    buildClearScreenEvent,
    buildCommitEvent,
    buildMouseHandlerStore,
    type CanvasWrapper,
    CanvasWrapperImpl,
    handleMouseDown,
    handleMouseUp,
    handleMouseMove,
    type AppConfig,
    processAppEvent,
  } from '@vighnesh153/drawing-app';

  import { classes } from '@/utils';
  import {
    brushThicknessStore,
    colorStore,
    drawingEventModeStore,
    isRedoAvailableStore,
    isUndoAvailableStore,
    eventsManagerStore,
    pendingQueueStore,
  } from '@/store/projects/drawing-app';

  import Toolbar from './Toolbar.svelte';

  let canvasElement: HTMLCanvasElement;
  let canvasWrapper: CanvasWrapper;
  let mouseHandlerStore = buildMouseHandlerStore();

  const colors: IColor[] = Object.values(Color);
  const brushThicknessValues = [
    BrushThickness.xs,
    BrushThickness.sm,
    BrushThickness.md,
    BrushThickness.lg,
    BrushThickness.xl,
  ];

  $: {
    if (canvasWrapper) {
      processAppEvent(canvasWrapper, $pendingQueueStore);
    }
  }

  function onModeChange(newMode: EventMode) {
    $drawingEventModeStore = newMode;
  }

  function onColorChange(newColor: IColor): void {
    $colorStore = newColor;
  }

  function onBrushThicknessChange(newBrushThickness: BrushThickness): void {
    $brushThicknessStore = newBrushThickness;
  }

  function onUndoButtonClick(): void {
    undo($eventsManagerStore);
    $eventsManagerStore = $eventsManagerStore;
  }

  function onRedoButtonClick(): void {
    redo($eventsManagerStore);
    $eventsManagerStore = $eventsManagerStore;
  }

  function onClearButtonClick(): void {
    publishEvents($eventsManagerStore, [
      buildClearScreenEvent({
        color: Color.White,
      }),
      buildCommitEvent(),
    ]);
    $eventsManagerStore = $eventsManagerStore;
  }

  function buildAppConfig(): AppConfig {
    return $drawingEventModeStore === 'draw'
      ? { mode: 'draw', brushThickness: $brushThicknessStore, color: $colorStore }
      : { mode: 'fill', color: $colorStore };
  }

  function onMouseDown(e: MouseEvent): void {
    handleMouseDown(mouseHandlerStore, e, canvasElement);
    $eventsManagerStore = $eventsManagerStore;
    mouseHandlerStore = mouseHandlerStore;
  }

  function onMouseUp(e: MouseEvent): void {
    handleMouseUp(mouseHandlerStore, $eventsManagerStore, buildAppConfig(), e, canvasElement);
    $eventsManagerStore = $eventsManagerStore;
    mouseHandlerStore = mouseHandlerStore;
  }

  function onMouseMove(e: MouseEvent): void {
    handleMouseMove(mouseHandlerStore, $eventsManagerStore, buildAppConfig(), e, canvasElement);
    $eventsManagerStore = $eventsManagerStore;
    mouseHandlerStore = mouseHandlerStore;
  }

  onMount(() => {
    canvasWrapper = new CanvasWrapperImpl(canvasElement, {
      width: canvasElement.clientWidth,
      height: canvasElement.clientHeight,
    });
  });
</script>

<div>
  <Toolbar
    {colors}
    {brushThicknessValues}
    selectedColor={$colorStore}
    selectedEventMode={$drawingEventModeStore}
    selectedBrushThickness={$brushThicknessStore}
    isRedoAvailable={$isRedoAvailableStore}
    isUndoAvailable={$isUndoAvailableStore}
    on:modeChange={(e) => onModeChange(e.detail.newMode)}
    on:colorChange={(e) => onColorChange(e.detail.newColor)}
    on:brushThicknessChange={(e) => onBrushThicknessChange(e.detail.newBrushThickness)}
    on:undo={onUndoButtonClick}
    on:redo={onRedoButtonClick}
    on:clear={onClearButtonClick}
  />

  <canvas
    bind:this={canvasElement}
    class={classes('mt-4 mx-auto bg-[white]', 'w-full max-w-3xl aspect-video')}
    on:mousedown={(e) => onMouseDown(e)}
    on:mouseup={(e) => onMouseUp(e)}
    on:mousemove={(e) => onMouseMove(e)}
  >
    <p>Sorry, canvas element is not supported in your browser</p>
  </canvas>
</div>

// tools-nodejs/vighnesh153-astro/website/src/components/projects/drawing-app/DrawingAppRoot.tsx
import { createEffect, createSignal, onCleanup, onMount } from "solid-js";
import { useStore } from "@nanostores/solid";

import {
  type AppConfig,
  BrushThickness,
  buildClearScreenEvent,
  buildCommitEvent,
  buildEventsManager,
  buildMouseHandlerStore,
  CanvasWrapperImpl,
  Color,
  type EventMode,
  type EventsManager,
  handleMouseDown,
  handleMouseMove,
  handleMouseUp,
  type IColor,
  type MouseHandlerStore,
  publishEvents,
  redo,
  undo,
} from "@vighnesh153/drawing-app";

import { classes } from "@/utils/index.ts";
import {
  brushThicknessStore,
  colorStore,
  drawingEventModeStore,
} from "@/store/projects/drawing-app/index.ts";

import { Toolbar } from "./Toolbar.tsx";

const colors: IColor[] = Object.values(Color);
const brushThicknessValues = [
  BrushThickness.xs,
  BrushThickness.sm,
  BrushThickness.md,
  BrushThickness.lg,
  BrushThickness.xl,
];

export function DrawingAppRoot() {
  let canvasElement!: HTMLCanvasElement;
  const [mouseHandlerStore, setMouseHandlerStore] = createSignal(
    buildMouseHandlerStore(),
  );
  const brushThickness = useStore(brushThicknessStore);
  const color = useStore(colorStore);
  const drawingEventMode = useStore(drawingEventModeStore);
  const [isRedoAvailable, setIsRedoAvailable] = createSignal(false);
  const [isUndoAvailable, setIsUndoAvailable] = createSignal(false);
  const [eventsManager, setEventsManager] = createSignal<EventsManager | null>(
    null,
  );

  const updateMouseHandlerStore = (store: MouseHandlerStore) => {
    setMouseHandlerStore(store);
  };

  const onModeChange = (newMode: EventMode) => {
    drawingEventModeStore.set(newMode);
  };

  const onColorChange = (newColor: IColor): void => {
    colorStore.set(newColor);
  };

  const onBrushThicknessChange = (newBrushThickness: BrushThickness): void => {
    brushThicknessStore.set(newBrushThickness);
  };

  const onUndoButtonClick = (): void => {
    const localEventsManager = eventsManager()!;
    undo(localEventsManager);
  };

  const onRedoButtonClick = (): void => {
    const localEventsManager = eventsManager()!;
    redo(localEventsManager);
  };

  const onClearButtonClick = (): void => {
    const localEventsManager = eventsManager()!;
    publishEvents(localEventsManager, [
      buildClearScreenEvent({
        color: Color.White,
      }),
      buildCommitEvent(),
    ]);
  };

  const buildAppConfig = (): AppConfig => {
    const c = color();
    const colorCloned = { ...c, rgba: { ...c.rgba } };
    return drawingEventMode() === "draw"
      ? { mode: "draw", brushThickness: brushThickness(), color: colorCloned }
      : { mode: "fill", color: colorCloned };
  };

  const onMouseDown = (e: MouseEvent): void => {
    const store = mouseHandlerStore();
    handleMouseDown(store, e, canvasElement);
    updateMouseHandlerStore(store);
  };

  const onMouseUp = (e: MouseEvent): void => {
    const store = mouseHandlerStore();
    handleMouseUp(
      store,
      eventsManager()!,
      buildAppConfig(),
      e,
      canvasElement,
    );
    updateMouseHandlerStore(store);
  };

  const onMouseMove = (e: MouseEvent): void => {
    const store = mouseHandlerStore();
    handleMouseMove(
      store,
      eventsManager()!,
      buildAppConfig(),
      e,
      canvasElement,
    );
    updateMouseHandlerStore(store);
  };

  onMount(() => {
    const cw = new CanvasWrapperImpl(canvasElement, {
      width: canvasElement.clientWidth,
      height: canvasElement.clientHeight,
    });
    setEventsManager(buildEventsManager(cw));
  });

  createEffect(() => {
    const interval = setInterval(() => {
      setIsRedoAvailable((eventsManager()?.redoEventsStack.size ?? 0) > 0);
      setIsUndoAvailable((eventsManager()?.undoEventsStack.size ?? 0) > 0);
    }, 16);
    onCleanup(() => {
      clearInterval(interval);
    });
  });

  return (
    <div>
      <Toolbar
        colors={colors}
        brushThicknessList={brushThicknessValues}
        selectedColor={color()}
        selectedEventMode={drawingEventMode()}
        selectedBrushThickness={brushThickness()}
        isRedoAvailable={isRedoAvailable()}
        isUndoAvailable={isUndoAvailable()}
        onModeChange={(newMode) => onModeChange(newMode)}
        onColorChange={(newColor) => onColorChange(newColor)}
        onBrushThicknessChange={(newBrushThickness) =>
          onBrushThicknessChange(newBrushThickness)}
        onUndoButtonClick={onUndoButtonClick}
        onRedoButtonClick={onRedoButtonClick}
        onClearButtonClick={onClearButtonClick}
      />

      <canvas
        ref={canvasElement}
        class={classes(
          "mt-4 mx-auto bg-[white]",
          "w-full max-w-3xl aspect-video",
        )}
        on:mousedown={(e) => onMouseDown(e)}
        on:mouseup={(e) => onMouseUp(e)}
        on:mousemove={(e) => onMouseMove(e)}
      >
        <p>Sorry, canvas element is not supported in your browser</p>
      </canvas>
    </div>
  );
}
