// nodejs-tools/nodejs-apps/vighnesh153-astro-svelte/src/components/projects/drawing-app/ModeButton.svelte
<script lang="ts">
  import { classes } from '@/utils';

  export let isSelected = false;
</script>

<div class="flex flex-col">
  <button
    class={classes(`p-2 rounded-full focus-visible:outline-secondary`)}
    class:outline={isSelected}
    class:outline-offset-4={isSelected}
    class:outline-2={isSelected}
    class:outline-secondary={isSelected}
    class:fill-text={isSelected}
    class:bg-secondary={isSelected}
    on:click
  >
    <slot />
  </button>
  {#if $$slots.title}
    <div class="mt-2 text-secondary" class:font-bold={isSelected} class:underline={isSelected}>
      <slot name="title">Title</slot>
    </div>
  {/if}
</div>

// tools-nodejs/vighnesh153-astro/website/src/components/projects/drawing-app/ModeButton.tsx
import { type JSX, type PropsWithChildren } from "react";
import { classes } from "@/utils/classes.ts";

export type ModeButtonProps = PropsWithChildren<{
  isSelected?: boolean;
  title?: string;
  onClick?: () => void;
}>;

export function ModeButton({
  isSelected = false,
  title,
  children,
  onClick,
}: ModeButtonProps): JSX.Element {
  return (
    <div className="flex flex-col">
      <button
        className={classes(
          `p-2 rounded-full focus-visible:outline-secondary`,
          isSelected &&
            "outline-offset-4 outline-2 outline-secondary fill-text bg-secondary",
        )}
        onClick={onClick}
      >
        {children}
      </button>
      {title && (
        <div
          className={classes(
            "mt-2 text-secondary",
            isSelected && "font-bold underline",
          )}
        >
          {title}
        </div>
      )}
    </div>
  );
}
