// nodejs-tools/nodejs-apps/vighnesh153-astro/src/components/projects/drawing-app/PopupButton.svelte
<script lang="ts">
  import { classes } from '@/utils/index.ts';

  export let buttonClasses: string = '';
  export let buttonStyles: string = '';

  type PopupState = 'open' | 'closed';

  let popupState: PopupState = 'closed';

  function togglePopup(state?: PopupState) {
    popupState = state !== undefined ? state : popupState === 'open' ? 'closed' : 'open';
  }
</script>

<div class="relative">
  <div class="flex flex-col">
    <button
      style={buttonStyles}
      class={classes(
        `w-11 h-11 grid place-items-center rounded-full border-2 border-secondary`,
        'focus-visible:outline-secondary',
        buttonClasses
      )}
      on:click={() => togglePopup()}
    >
      <slot />
    </button>
    {#if true || $$slots.title}
      <div class="mt-1 text-secondary">
        <slot name="title">Title</slot>
      </div>
    {/if}
  </div>
  {#if $$slots['popup-content'] && popupState === 'open'}
    <div class="absolute top-16 -translate-x-1/2 z-[1000000] w-fit p-6 bg-text shadow-2xl shadow-primary rounded-lg">
      <slot name="popup-content" {togglePopup} />
    </div>
  {/if}
</div>

// tools-nodejs/vighnesh153-astro/website/src/components/projects/drawing-app/PopupButton.tsx
import { children, createSignal, type JSX, Show } from "solid-js";
import { classes } from "@/utils/index.ts";

type PopupState = "open" | "closed";

export type PopupButton = {
  buttonClasses?: string;
  buttonStyles?: string;
  title?: string;
  popupContent: (togglePopup: (state?: PopupState) => void) => JSX.Element;
  children?: (togglePopup: (state?: PopupState) => void) => JSX.Element;
} & Pick<JSX.ButtonHTMLAttributes<HTMLButtonElement>, "onClick">;

export function PopupButton(props: PopupButton) {
  const [popupState, setPopupState] = createSignal<PopupState>("closed");

  const togglePopup = (state?: PopupState) => {
    setPopupState(
      state !== undefined ? state : popupState() === "open" ? "closed" : "open",
    );
  };

  const safeChildren = children(() => props.children?.(togglePopup));

  return (
    <div class="relative">
      <div class="flex flex-col">
        <button
          style={props.buttonStyles}
          class={classes(
            `w-11 h-11 grid place-items-center rounded-full border-2 border-secondary`,
            "focus-visible:outline-secondary",
            props.buttonClasses,
          )}
          onClick={() => togglePopup()}
        >
          {safeChildren()}
        </button>

        <div class="mt-1 text-secondary">
          {props.title ?? "Title"}
        </div>
      </div>
      <Show when={popupState() === "open"}>
        <div class="absolute top-16 -translate-x-1/2 z-[1000000] w-fit p-6 bg-text shadow-2xl shadow-primary rounded-lg">
          {props.popupContent(togglePopup)}
        </div>
      </Show>
    </div>
  );
}
