// tools-nodejs/vighnesh153-astro/website/src/components/projects/tsx-playground/CodePreview.tsx
import { baseIframeHtmlCode } from "@vighnesh153/tsx-bundler";
import { type JSX, useEffect, useRef } from "react";

export type CodePreviewResult_Bundling = {
  status: "bundling";
};
export type CodePreviewResult_Success = {
  status: "success";
  outputCode: string;
};

export type CodePreviewResult_Error = {
  status: "error";
  bundleError: string;
};

export type CodePreviewResult =
  | CodePreviewResult_Bundling
  | CodePreviewResult_Success
  | CodePreviewResult_Error;

export type CodePreviewProps = {
  result?: CodePreviewResult;
};

export function CodePreview({
  result = { status: "bundling" },
}: CodePreviewProps): JSX.Element {
  const previewIframe = useRef<HTMLIFrameElement>(null);

  useEffect(() => {
    if (result.status === "success" && previewIframe.current) {
      const outputCode = result.outputCode;
      previewIframe.current.srcdoc = baseIframeHtmlCode;
      const timeout = setTimeout(() => {
        previewIframe.current?.contentWindow?.postMessage(outputCode, "*");
      }, 50);
      return () => clearTimeout(timeout);
    }
  }, [result]);

  return (
    <div className="w-full h-full p-4 bg-text">
      {result.status === "bundling"
        ? <div className="text-background">Bundling...</div>
        : result.status === "error"
        ? (
          <div className="text-[red] whitespace-pre overflow-x-auto">
            <div className="font-bold text-xl">
              Some error occurred while bundling
            </div>
            <div className="whitespace-break-spaces">
              {result.bundleError}
            </div>
          </div>
        )
        : (
          <iframe
            ref={previewIframe}
            className="w-full h-full"
            title="preview"
            sandbox="allow-same-origin allow-scripts"
            srcDoc={baseIframeHtmlCode}
          />
        )}
    </div>
  );
}

// tools-nodejs/vighnesh153-astro/src/components/projects/tsx-playground/CodePreview.svelte
<script context="module" lang="ts">
  export type CodePreviewResult =
    | {
        status: 'bundling';
      }
    | {
        status: 'success';
        outputCode: string;
      }
    | {
        status: 'error';
        bundleError: string;
      };
</script>

<script lang="ts">
  import { baseIframeHtmlCode } from '@vighnesh153/tsx-bundler';

  export let result: CodePreviewResult = {
    status: 'bundling',
  };

  let previewIframe: HTMLIFrameElement;

  $: (() => {
    if (result.status === 'success' && previewIframe) {
      const outputCode = result.outputCode;
      previewIframe.srcdoc = baseIframeHtmlCode;
      setTimeout(() => {
        previewIframe.contentWindow?.postMessage(outputCode);
      }, 50);
    }
  })();
</script>

<div class="w-full h-full p-4 bg-text">
  {#if result.status === 'bundling'}
    <div class="text-background">Bundling...</div>
  {:else if result.status === 'error'}
    <div class="text-[red] whitespace-pre overflow-x-auto">
      <div class="font-bold text-xl">Some error occurred while bundling</div>
      <div>{result.bundleError}</div>
    </div>
  {:else}
    <iframe
      bind:this={previewIframe}
      class="w-full h-full"
      title="preview"
      sandbox="allow-same-origin allow-scripts"
      srcdoc={baseIframeHtmlCode}
    />
  {/if}
</div>
