// tools-nodejs/vighnesh153-astro/website/src/components/snackbar/SnackbarHost.tsx
import type { JSX } from "react";
import { useStore } from "@nanostores/react";
import { snackbarList } from "@/store/snackbar.ts";
import { Snackbar } from "./Snackbar.tsx";

export function SnackbarHost(): JSX.Element {
  const $snackbarList = useStore(snackbarList);

  return (
    <div className="fixed top-10 right-10 z-(--z-snackbar)">
      {$snackbarList.map((snackbar) => (
        <Snackbar key={snackbar.id} {...snackbar} />
      ))}
    </div>
  );
}

// nodejs-tools/nodejs-apps/vighnesh153-astro/src/components/solid/snackbar/SnackbarHost.tsx
import { For, type JSX } from 'solid-js';
import { useStore } from '@nanostores/solid';
import { snackbarList } from '@/stores/snackbar.ts';
import { Snackbar } from './Snackbar.tsx';

export function SnackbarHost(): JSX.Element {
  const $snackbarList = useStore(snackbarList);

  return (
    <div class="fixed top-10 right-10 z-snackbar">
      <For each={$snackbarList()}>{(snackbar) => <Snackbar {...snackbar} />}</For>
    </div>
  );
}
