// nodejs-tools/nodejs-apps/vighnesh153-astro/src/components/solid/buttons/Button.tsx
import { children, mergeProps, splitProps, type JSX, type ParentProps } from 'solid-js';

import { classes } from '@/utils';

export type ButtonProps = ParentProps<{
  variant?: 'primary' | 'secondary';
}> &
  JSX.ButtonHTMLAttributes<HTMLButtonElement>;

export function Button(incomingProps: ButtonProps): JSX.Element {
  const [local, buttonProps] = splitProps(mergeProps<ButtonProps[]>({ variant: 'secondary' }, incomingProps), [
    'variant',
    'class',
    'children',
  ]);
  const c = children(() => local.children);
  return (
    <button {...buttonProps} class={classes(local.class, `${local.variant}-button`)}>
      {c()}
    </button>
  );
}

// tools-nodejs/vighnesh153-astro/website/src/components/buttons/Button.tsx
import { type ButtonHTMLAttributes, type JSX } from "react";

import styles from "./Button.module.scss";

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary";
}

export function Button({
  variant = "secondary",
  ...props
}: ButtonProps): JSX.Element {
  if (variant == "primary") {
    return <PrimaryButton {...props} />;
  }
  if (variant == "secondary") {
    return <SecondaryButton {...props} />;
  }

  return <button {...props} />;
}

function PrimaryButton(
  props: ButtonHTMLAttributes<HTMLButtonElement>,
): JSX.Element {
  return (
    <button
      {...props}
      className={`${styles.btn} ${styles["btn-primary"]} ${props.className}`}
    />
  );
}

function SecondaryButton(
  props: ButtonHTMLAttributes<HTMLButtonElement>,
): JSX.Element {
  return (
    <button
      {...props}
      className={`${styles.btn} ${styles["btn-secondary"]} ${props.className}`}
    />
  );
}
