// nodejs-tools/nodejs-apps/vighnesh153-astro/src/components/solid/buttons/GoogleSignInButton.tsx
import { type ParentProps } from 'solid-js';

import { classes, initiateLoginWithGoogle } from '@/utils/index.ts';
import { GoogleIcon } from '@/icons/solid/GoogleIcon.tsx';

export type GoogleSignInButtonProps = ParentProps;

export function GoogleSignInButton() {
  return (
    <button
      onClick={initiateLoginWithGoogle}
      class={classes(`
      min-w-fit px-5 py-2 rounded-md
      flex gap-2 items-center
      bg-text
      text-secondary
      `)}
    >
      <GoogleIcon class="inline-block w-5 aspect-square" />
      Sign in
    </button>
  );
}

// tools-nodejs/vighnesh153-astro/website/src/components/buttons/GoogleSignInButton.tsx
import type { JSX } from "react";

import { initiateLoginWithGoogle } from "@/utils/auth.ts";
import { classes } from "@/utils/classes.ts";
import { GoogleIcon } from "@/icons/GoogleIcon.tsx";

export function GoogleSignInButton(): JSX.Element {
  return (
    <button
      onClick={initiateLoginWithGoogle}
      className={classes(`
      min-w-fit px-5 py-2 rounded-md
      flex gap-2 items-center
      bg-text
      text-secondary
      `)}
    >
      <GoogleIcon class="inline-block w-5 aspect-square" />
      Sign in
    </button>
  );
}
