// nodejs-tools/nodejs-apps/vighnesh153-astro-svelte/src/components/tools/PrimesCalculators.svelte
<script lang="ts">
  import FindPreviousAndNextPrime from './FindPreviousAndNextPrime.svelte';
  import FindPrimesInRange from './FindPrimesInRange.svelte';
  import IsPrime from './IsPrime.svelte';
</script>

<h2 class="text-2xl">Primes</h2>

<hr class="mt-2 text-text4" />

<div class="mt-4">
  <IsPrime />
</div>

<hr class="mt-2 text-text4" />

<div class="mt-4">
  <FindPreviousAndNextPrime />
</div>

<hr class="mt-2 text-text4" />

<div class="mt-4">
  <FindPrimesInRange />
</div>

// tools-nodejs/vighnesh153-astro/website/src/components/tools/PrimesCalculators.tsx
import type { JSX } from "react";

import { IsPrime } from "./IsPrime.tsx";
import { FindPreviousAndNextPrime } from "./FindPreviousAndNextPrime.tsx";
import { FindPrimesInRange } from "./FindPrimesInRange.tsx";

export function PrimesCalculators(): JSX.Element {
  return (
    <>
      <h2 className="text-2xl">Primes</h2>

      <hr className="mt-2 text-text4" />

      <div className="mt-4">
        <IsPrime />
      </div>

      <hr className="mt-2 text-text4" />

      <div className="mt-4">
        <FindPreviousAndNextPrime />
      </div>

      <hr className="mt-2 text-text4" />

      <div className="mt-4">
        <FindPrimesInRange />
      </div>
    </>
  );
}
