// tools-nodejs/vighnesh153-astro/website/src/components/projects/drawing-app/ActionButton.tsx
import { type ButtonHTMLAttributes, type JSX } from "react";
import { not } from "@vighnesh153/tools";
import { classes } from "@/utils/classes.ts";

export type ActionButtonProps = {
  title: string;
} & ButtonHTMLAttributes<HTMLButtonElement>;

export function ActionButton({
  title,
  children,
  ...props
}: ActionButtonProps): JSX.Element {
  const disabled = props.disabled;

  return (
    <div className="flex flex-col">
      <button
        {...props}
        className={classes(
          "w-[40px] aspect-square rounded-full grid place-items-center border-2",
          "focus-visible:outline-secondary",
          disabled &&
            "cursor-not-allowed stroke-[#aeaeae] fill-[#aeaeae] border-[#aeaeae]",
          not(disabled) &&
            "stroke-secondary fill-secondary border-secondary",
        )}
      >
        {children}
      </button>
      <div className="mt-2 text-secondary">
        {title ?? "Title"}
      </div>
    </div>
  );
}

// nodejs-tools/nodejs-apps/vighnesh153-astro-svelte/src/components/projects/drawing-app/ActionButton.svelte
<script lang="ts">
  import { classes } from '@/utils';
</script>

<div class="flex flex-col">
  <button
    class={classes(
      'w-[40px] aspect-square rounded-full grid place-items-center border-2 border-secondary',
      'focus-visible:outline-secondary'
    )}
    on:click
  >
    <slot />
  </button>
  <div class="mt-2 text-secondary">
    <slot name="title">Title</slot>
  </div>
</div>
