// tools-nodejs/vighnesh153-astro/website/src/components/projects/drawing-app/PopupButton.tsx
import {
  type ButtonHTMLAttributes,
  type JSX,
  type ReactNode,
  useState,
} from "react";
import { classes } from "@/utils/classes.ts";

type PopupState = "open" | "closed";

export type PopupButtonProps = {
  buttonClasses?: string;
  buttonStyles?: React.CSSProperties;
  title?: string;
  popupContent: (togglePopup: (state?: PopupState) => void) => ReactNode;
  children?: (togglePopup: (state?: PopupState) => void) => ReactNode;
} & Pick<ButtonHTMLAttributes<HTMLButtonElement>, "onClick">;

export function PopupButton(props: PopupButtonProps): JSX.Element {
  const [popupState, setPopupState] = useState<PopupState>("closed");

  const togglePopup = (state?: PopupState) => {
    setPopupState((old) =>
      state !== undefined ? state : old === "open" ? "closed" : "open"
    );
  };

  return (
    <div className="relative">
      <div className="flex flex-col">
        <button
          style={props.buttonStyles}
          className={classes(
            `w-11 h-11 grid place-items-center rounded-full border-2 border-secondary`,
            "focus-visible:outline-secondary",
            props.buttonClasses,
          )}
          onClick={() => togglePopup()}
        >
          {props.children?.(togglePopup)}
        </button>

        <div className="mt-1 text-secondary">
          {props.title ?? "Title"}
        </div>
      </div>
      {popupState === "open" && (
        <div className="absolute top-16 -translate-x-1/2 z-[1000000] w-fit p-6 bg-text shadow-2xl shadow-primary rounded-lg">
          {props.popupContent(togglePopup)}
        </div>
      )}
    </div>
  );
}

// nodejs-tools/nodejs-apps/vighnesh153-astro-svelte/src/components/projects/drawing-app/PopupButton.svelte
<script lang="ts">
  import { classes } from '@/utils';

  export let buttonClasses: string = '';
  export let buttonStyles: string = '';

  type PopupState = 'open' | 'closed';

  let popupState: PopupState = 'closed';

  function togglePopup(state?: PopupState) {
    // prettier-ignore
    popupState = state !== undefined 
      ? state 
      : (popupState === 'open' ? 'closed' : 'open');
  }
</script>

<div class="relative">
  <div class="flex flex-col">
    <button
      style={buttonStyles}
      class={classes(`w-11 h-11 grid place-items-center rounded-full border-2 border-secondary`, buttonClasses)}
      on:click={() => togglePopup()}
    >
      <slot />
    </button>
    {#if true || $$slots.title}
      <div class="mt-1 text-secondary">
        <slot name="title">Title</slot>
      </div>
    {/if}
  </div>
  {#if $$slots['popup-content'] && popupState === 'open'}
    <div class="absolute top-16 -translate-x-1/2 z-[1000000] w-fit p-6 bg-text shadow-2xl shadow-primary rounded-lg">
      <slot name="popup-content" {togglePopup} />
    </div>
  {/if}
</div>
