// tools-nodejs/vighnesh153-astro/website/src/components/projects/games/brick-breaker-game/BrickBreakerGameRoot.tsx
import { createSignal, onMount } from "solid-js";
import {
  BrickBreakerGame,
  type CanvasWrapper,
  CanvasWrapperImpl,
} from "@vighnesh153/tools-browser/graphics_programming";

export function BrickBreakerGameRoot() {
  let canvasElement!: HTMLCanvasElement;
  const [game, setGame] = createSignal<BrickBreakerGame>();

  const handleMouseMove = (e: MouseEvent) => {
    game()?.handleMouseMove(e, document.documentElement.scrollLeft);
  };

  onMount(() => {
    const canvasWrapper = new CanvasWrapperImpl(canvasElement);
    const gameInstance = new BrickBreakerGame(canvasWrapper, {
      onGameOver() {
        gameInstance.stop();
        alert("Game over! You win!");
        window.location.reload();
      },
    });
    const frames = gameInstance.start();
    function showNextFrame() {
      if (!frames.next().done) {
        requestAnimationFrame(showNextFrame);
      }
    }
    showNextFrame();

    setGame(gameInstance);
  });

  return (
    <canvas
      class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text"
      ref={canvasElement}
      onMouseMove={handleMouseMove}
    >
      Sorry your browser doesn't support the canvas element
    </canvas>
  );
}

// tools-nodejs/vighnesh153-astro/src/components/projects/games/brick-breaker-game/BrickBreakerGameRoot.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import {
    BrickBreakerGame,
    CanvasWrapperImpl,
    type CanvasWrapper,
  } from "@vighnesh153/tools-browser/graphics_programming";

  let canvasElement: HTMLCanvasElement;
  let canvasWrapper: CanvasWrapper;
  let game: BrickBreakerGame;

  function handleMouseMove(e: MouseEvent) {
    game.handleMouseMove(e, document.documentElement.scrollLeft);
  }

  function newGame() {
    if (canvasWrapper) {
      game = new BrickBreakerGame(canvasWrapper, {
        onGameOver() {
          game.stop();
          alert("Game over! You win!");
          window.location.reload();
        },
      });
      const frames = game.start();
      function showNextFrame() {
        if (!frames.next().done) {
          requestAnimationFrame(showNextFrame);
        }
      }
      showNextFrame();
    }
  }

  onMount(() => {
    canvasWrapper = new CanvasWrapperImpl(canvasElement);
    newGame();
  });
</script>

<canvas
  class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text"
  bind:this={canvasElement}
  on:mousemove={handleMouseMove}
>
  Sorry your browser doesn't support the canvas element
</canvas>
