// tools-nodejs/vighnesh153-astro/website/src/components/projects/graphics/pseudo-hilbert-curve/PseudoHilbertCurveRoot.tsx
import { createSignal, For, type JSX, onMount } from "solid-js";

import { range } from "@vighnesh153/tools";

import {
  type CanvasWrapper,
  CanvasWrapperImpl,
  PseudoHilbertCurveGame,
} from "@vighnesh153/tools-browser/graphics_programming";

export function PseudoHilbertCurveRoot() {
  let canvasElement!: HTMLCanvasElement;

  const [game, setGame] = createSignal<PseudoHilbertCurveGame>();
  const [canvasWrapper, setCanvasWrapper] = createSignal<CanvasWrapper>();

  let minLevel = 2;
  let maxLevel = 6;
  let initialValue = 4;
  const [level, setLevel] = createSignal<number>();

  const newGame = () => {
    game()?.stop();
    game()?.clear();

    if (canvasWrapper()) {
      const gameInstance = new PseudoHilbertCurveGame(canvasWrapper()!);
      const frames = gameInstance.start(level()!);
      function showNextFrame() {
        if (!frames.next().done) {
          requestAnimationFrame(showNextFrame);
        }
      }
      showNextFrame();

      setGame(gameInstance);
    }
  };

  const updateLevel: JSX.ChangeEventHandler<HTMLSelectElement, Event> = (e) => {
    setLevel(+e.target.value);
    newGame();
  };

  onMount(() => {
    setLevel(initialValue);
    setCanvasWrapper(new CanvasWrapperImpl(canvasElement));
    newGame();
  });

  return (
    <>
      <div class="flex flex-col items-center gap-1">
        <label for="level">Level</label>
        <select
          name="level"
          id="level"
          class="min-w-[100px] text-secondary"
          value={level()}
          onChange={updateLevel}
        >
          <For each={Array.from(range(minLevel, maxLevel))}>
            {(rangeLevel) => <option value={rangeLevel}>{rangeLevel}</option>}
          </For>
        </select>
      </div>
      <canvas
        class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text"
        ref={canvasElement}
      >
        Sorry your browser doesn't support the canvas element
      </canvas>
    </>
  );
}

// nodejs-tools/nodejs-apps/vighnesh153-astro/src/components/projects/graphics/pseudo-hilbert-curve/PseudoHilbertCurveRoot.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  import { PseudoHilbertCurveGame, CanvasWrapperImpl } from '@vighnesh153/graphics-programming';
  import type { CanvasWrapper } from '@vighnesh153/graphics-programming';
  import { range } from '@vighnesh153/tools';

  let canvasElement: HTMLCanvasElement;
  let canvasWrapper: CanvasWrapper;
  let game: PseudoHilbertCurveGame;

  let level = 4;
  let minLevel = 2;
  let maxLevel = 6;

  function newGame() {
    if (game) {
      game.stop();
      game.clear();
    }

    if (canvasWrapper) {
      game = new PseudoHilbertCurveGame(canvasWrapper);
      const frames = game.start(level);
      function showNextFrame() {
        if (!frames.next().done) {
          requestAnimationFrame(showNextFrame);
        }
      }
      showNextFrame();
    }
  }

  onMount(() => {
    canvasWrapper = new CanvasWrapperImpl(canvasElement);
    newGame();
  });

  $: {
    // this log is needed so that this block runs when level changes
    console.log(`Level changed: ${level}`);
    newGame();
  }
</script>

<div class="flex flex-col items-center gap-1">
  <label for="level">Level</label>
  <select name="level" id="level" class="min-w-[100px] text-secondary" bind:value={level}>
    {#each range(minLevel, maxLevel) as rangeLevel (rangeLevel)}
      <option value={rangeLevel}>{rangeLevel}</option>
    {/each}
  </select>
</div>
<canvas class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text" bind:this={canvasElement}>
  Sorry your browser doesn't support the canvas element
</canvas>
