// nodejs-tools/nodejs-apps/vighnesh153-astro/src/components/Button.svelte
<script lang="ts">
  import { classes } from '@/utils/index.ts';
  import type { HTMLButtonAttributes } from 'svelte/elements';

  interface $$Props extends HTMLButtonAttributes {
    variant?: 'primary' | 'secondary';
  }
  export let variant: $$Props['variant'] = 'secondary';

  const { class: className } = $$props;
</script>

<button {...$$props} class={classes(className, `${variant}-button`)} on:click>
  <slot />
</button>

// nodejs-tools/nodejs-apps/vighnesh153-astro/src/components/solid/buttons/Button.tsx
import { children, mergeProps, splitProps, type JSX, type ParentProps } from 'solid-js';

import { classes } from '@/utils/index.ts';

export type ButtonProps = ParentProps<{
  variant?: 'primary' | 'secondary';
}> &
  JSX.ButtonHTMLAttributes<HTMLButtonElement>;

export function Button(incomingProps: ButtonProps): JSX.Element {
  const [local, buttonProps] = splitProps(mergeProps<ButtonProps[]>({ variant: 'secondary' }, incomingProps), [
    'variant',
    'class',
    'children',
  ]);
  const c = children(() => local.children);
  return (
    <button {...buttonProps} class={classes(local.class, `${local.variant}-button`)}>
      {c()}
    </button>
  );
}
