// tools-nodejs/vighnesh153-astro/website/src/components/Link.svelte
<script lang="ts">
  import { classes } from "@/utils/index.ts";
  import type { HTMLAnchorAttributes } from "svelte/elements";

  interface $$Props extends HTMLAnchorAttributes {
    linkType?: "regular" | "primary-btn" | "secondary-btn";
  }
  export let linkType: $$Props["linkType"] = "regular";

  const { class: className, href } = $$props;
</script>

<a {...$$props} {href} class={classes(className, `${linkType}-link`)} on:click>
  <slot />
</a>

// tools-nodejs/vighnesh153-astro/website/src/components/Link.tsx
import {
  children,
  type JSX,
  mergeProps,
  type ParentProps,
  splitProps,
} from "solid-js";
import { classes } from "@/utils";

export type LinkProps =
  & ParentProps<{
    linkType?: "regular" | "primary-btn" | "secondary-btn";
  }>
  & JSX.AnchorHTMLAttributes<HTMLAnchorElement>;

export function Link(incomingProps: LinkProps) {
  const [localProps, other] = splitProps(
    mergeProps<LinkProps[]>({ linkType: "regular" }, incomingProps),
    ["href", "class", "linkType", "children"],
  );
  const safeChildren = children(() => localProps.children);

  return (
    <a
      {...other}
      href={localProps.href}
      class={classes(localProps.class, `${localProps.linkType}-link`)}
    >
      {safeChildren()}
    </a>
  );
}
