// tools-nodejs/vighnesh153-astro/src/components/projects/games/snake-game/SnakeGameRoot.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import {
    SnakeGame,
    CanvasWrapperImpl,
    type CanvasWrapper,
  } from "@vighnesh153/tools-browser/graphics_programming";

  let canvasElement: HTMLCanvasElement;
  let canvasWrapper: CanvasWrapper;
  let game: SnakeGame;

  function keyupEventListener(e: KeyboardEvent) {
    e.preventDefault();
    if (["ArrowDown", "s", "S"].includes(e.key)) {
      game.changeDirection("bottom");
    } else if (["ArrowUp", "w", "W"].includes(e.key)) {
      game.changeDirection("top");
    } else if (["ArrowLeft", "a", "A"].includes(e.key)) {
      game.changeDirection("left");
    } else if (["ArrowRight", "d", "D"].includes(e.key)) {
      game.changeDirection("right");
    }
  }

  function newGame() {
    if (canvasWrapper) {
      game = new SnakeGame(canvasWrapper);
      canvasElement.focus();
      const frames = game.start();
      function showNextFrame() {
        if (!frames.next().done) {
          requestAnimationFrame(showNextFrame);
        }
      }
      showNextFrame();
    }
  }

  onMount(() => {
    canvasWrapper = new CanvasWrapperImpl(canvasElement);
    newGame();
  });
</script>

<canvas
  class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text"
  bind:this={canvasElement}
  on:keyup={keyupEventListener}
  tabindex="0"
>
  Sorry your browser doesn't support the canvas element
</canvas>

// tools-nodejs/vighnesh153-astro/website/src/components/projects/games/snake-game/SnakeGameRoot.tsx
import { createSignal, onMount } from "solid-js";
import {
  CanvasWrapperImpl,
  SnakeGame,
} from "@vighnesh153/tools-browser/graphics_programming";

export function SnakeGameRoot() {
  let canvasElement!: HTMLCanvasElement;
  const [game, setGame] = createSignal<SnakeGame>();

  const keyupEventListener = (e: KeyboardEvent) => {
    e.preventDefault();
    if (["ArrowDown", "s", "S"].includes(e.key)) {
      game()?.changeDirection("bottom");
    } else if (["ArrowUp", "w", "W"].includes(e.key)) {
      game()?.changeDirection("top");
    } else if (["ArrowLeft", "a", "A"].includes(e.key)) {
      game()?.changeDirection("left");
    } else if (["ArrowRight", "d", "D"].includes(e.key)) {
      game()?.changeDirection("right");
    }
  };

  onMount(() => {
    const canvasWrapper = new CanvasWrapperImpl(canvasElement);
    const gameInstance = new SnakeGame(canvasWrapper);
    canvasElement.focus();
    const frames = gameInstance.start();
    function showNextFrame() {
      if (!frames.next().done) {
        requestAnimationFrame(showNextFrame);
      }
    }
    showNextFrame();

    setGame(gameInstance);
  });

  return (
    <canvas
      class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text"
      ref={canvasElement}
      onKeyUp={keyupEventListener}
      tabindex="0"
    >
      Sorry your browser doesn't support the canvas element
    </canvas>
  );
}
