// tools-nodejs/vighnesh153-astro/website/src/components/tools/FindPrimesInRange.tsx
import { type JSX, useState } from "react";

import { Button } from "@/components/buttons/index.ts";
import { isPrime, Queue } from "@vighnesh153/tools";

export function FindPrimesInRange(): JSX.Element {
  const [minN, setMinN] = useState(0);
  const [maxN, setMaxN] = useState(0);
  const [primesInRange, setPrimesInRange] = useState<number[]>([]);

  const onFind = () => {
    const start = Math.ceil(minN);
    const end = Math.floor(maxN);

    const primes = new Queue<number>();
    for (let i = start; i <= end; i++) {
      if (isPrime(i)) {
        primes.pushRight(i);
      }
    }
    setPrimesInRange(primes.toArray());
  };

  return (
    <>
      <p className=" text-text">
        Find primes in between a range (start and end inclusive)
      </p>

      <div className="mt-4 flex gap-6 items-center">
        <input
          className="p-2 text-secondary"
          type="number"
          value={minN}
          onChange={(e) => setMinN(+e.target.value)}
        />
        <input
          className="p-2 text-secondary"
          type="number"
          value={maxN}
          onChange={(e) => setMaxN(+e.target.value)}
        />

        <Button variant="primary" onClick={onFind}>Find</Button>
      </div>

      <div>
        {primesInRange.length > 0 && (
          <>
            <p className="text-text2">
              Count: <span className="text-accent">{primesInRange.length}</span>
            </p>
            <p className="text-text2">
              Values:{" "}
              <span className="text-text">{primesInRange.join(", ")}</span>
            </p>
          </>
        )}
      </div>
    </>
  );
}

// nodejs-tools/nodejs-apps/vighnesh153-astro/src/components/tools/FindPrimesInRange.svelte
<script lang="ts">
  import Button from '@/components/Button.svelte';
  import { Queue, isPrime } from '@vighnesh153/tools';

  let minN: number = 0;
  let maxN: number = 0;
  let primesInRange: number[] = [];

  function onFind() {
    const start = Math.ceil(minN);
    const end = Math.floor(maxN);

    const primes = new Queue<number>();
    for (let i = start; i <= end; i++) {
      if (isPrime(i)) {
        primes.pushRight(i);
      }
    }
    primesInRange = primes.toArray();
  }
</script>

<p class=" text-text">Find primes in between a range</p>

<div class="mt-4 flex gap-6 items-center">
  <input class="p-2 text-secondary" type="number" bind:value={minN} />
  <input class="p-2 text-secondary" type="number" bind:value={maxN} />

  <Button variant="primary" on:click={onFind}>Find</Button>
</div>

<div>
  {#if primesInRange.length > 0}
    <p class="text-text2">Count: <span class="text-accent">{primesInRange.length}</span></p>
    <p class="text-text2">Values: <span class="text-text">{primesInRange.join(', ')}</span></p>
  {/if}
</div>
