// tools-nodejs/vighnesh153-astro/website/src/components/projects/games/flappy-block-game/FlappyBlockGameRoot.tsx
import { createSignal, onMount } from "solid-js";
import {
  CanvasWrapperImpl,
  FlappyBlockGame,
} from "@vighnesh153/tools-browser/graphics_programming";

export function FlappyBlockGameRoot() {
  let canvasElement!: HTMLCanvasElement;
  const [game, setGame] = createSignal<FlappyBlockGame>();

  const handleKeyPress = (e: KeyboardEvent) => {
    if (e.key === " ") {
      game()?.handleSpacebarPress();
    }
    if (e.key === "Enter") {
      game()?.handleEnterPress();
    }
  };

  onMount(() => {
    const canvasWrapper = new CanvasWrapperImpl(canvasElement);
    const gameInstance = new FlappyBlockGame(canvasWrapper);
    canvasElement.focus();
    const frames = gameInstance.start();
    function showNextFrame() {
      if (!frames.next().done) {
        requestAnimationFrame(showNextFrame);
      }
    }
    showNextFrame();

    setGame(gameInstance);
  });

  return (
    <canvas
      class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text"
      tabindex="0"
      ref={canvasElement}
      onKeyPress={handleKeyPress}
    >
      Sorry your browser doesn't support the canvas element
    </canvas>
  );
}

// tools-nodejs/vighnesh153-astro/src/components/projects/games/flappy-block-game/FlappyBlockGameRoot.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import {
    FlappyBlockGame,
    CanvasWrapperImpl,
    type CanvasWrapper,
  } from "@vighnesh153/tools-browser/graphics_programming";

  let canvasElement: HTMLCanvasElement;
  let canvasWrapper: CanvasWrapper;
  let game: FlappyBlockGame;

  function handleKeyPress(e: KeyboardEvent) {
    if (e.key === " ") {
      game.handleSpacebarPress();
    }
    if (e.key === "Enter") {
      game.handleEnterPress();
    }
  }

  function newGame() {
    if (canvasWrapper) {
      game = new FlappyBlockGame(canvasWrapper);
      canvasElement.focus();
      const frames = game.start();
      function showNextFrame() {
        if (!frames.next().done) {
          requestAnimationFrame(showNextFrame);
        }
      }
      showNextFrame();
    }
  }

  onMount(() => {
    canvasWrapper = new CanvasWrapperImpl(canvasElement);
    newGame();
  });
</script>

<canvas
  class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text"
  tabindex="0"
  bind:this={canvasElement}
  on:keypress={handleKeyPress}
>
  Sorry your browser doesn't support the canvas element
</canvas>
