// tools-nodejs/vighnesh153-astro/website/src/components/projects/graphics/sierpinskis-triangle/SierpinskisTriangleRoot.tsx
import { createSignal, onMount } from "solid-js";

import {
  CanvasWrapperImpl,
  SierpinskisTriangleGame,
  SierpinskisTriangleGameManager,
} from "@vighnesh153/tools-browser/graphics_programming";

import { Button } from "@/components/buttons/index.ts";
import { createSnackbar } from "@/store/snackbar.ts";

export function SierpinskisTriangleRoot() {
  let canvasElement!: HTMLCanvasElement;

  const [gameManager, setGameManager] = createSignal<
    SierpinskisTriangleGameManager
  >();

  const start = () => {
    const frames = gameManager()?.start();
    if (!frames) {
      return;
    }
    const showNextFrame = () => {
      if (!frames.next().done) {
        requestAnimationFrame(showNextFrame);
      }
    };
    showNextFrame();
  };

  const stop = () => {
    gameManager()?.stop();
    createSnackbar({
      type: "warn",
      message: "Rendering stopped. Refresh page to restart...",
      autoDismissible: false,
      manualDismissible: true,
    });
  };

  onMount(() => {
    const canvasWrapper = new CanvasWrapperImpl(canvasElement);
    const game = new SierpinskisTriangleGame(canvasWrapper, {
      pointRadius: 1,
      speed: 6,
    });
    setGameManager(new SierpinskisTriangleGameManager(game));
    start();
  });

  return (
    <>
      <div class="flex justify-center gap-2">
        <Button variant="primary" onClick={stop}>Stop rendering</Button>
      </div>

      <canvas
        class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text"
        ref={canvasElement}
      >
        Sorry your browser doesn't support the canvas element
      </canvas>
    </>
  );
}

// nodejs-tools/nodejs-apps/vighnesh153-astro-svelte/src/components/projects/graphics/sierpinskis-triangle/SierpinskisTriangleRoot.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  import {
    SierpinskisTriangleGame,
    SierpinskisTriangleGameManager,
    CanvasWrapperImpl,
  } from '@vighnesh153/graphics-programming';

  import Button from '@/components/Button.svelte';

  let canvasElement: HTMLCanvasElement;
  let game: SierpinskisTriangleGame;
  let gameManager: SierpinskisTriangleGameManager;

  function start() {
    const frames = gameManager.start();
    function showNextFrame() {
      if (!frames.next().done) {
        requestAnimationFrame(showNextFrame);
      }
    }
    showNextFrame();
  }

  function stop() {
    gameManager.stop();
  }

  onMount(() => {
    const dpr = window.devicePixelRatio ?? 1;
    const canvasWrapper = new CanvasWrapperImpl(canvasElement, { devicePixelRatio: dpr });
    game = new SierpinskisTriangleGame(canvasWrapper, { pointRadius: 1, speed: dpr * 4 });
    gameManager = new SierpinskisTriangleGameManager(game);

    start();
  });
</script>

<div class="flex justify-center gap-2">
  <Button variant="primary" on:click={stop}>Stop rendering</Button>
</div>

<canvas class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text" bind:this={canvasElement}>
  Sorry your browser doesn't support the canvas element
</canvas>
