// tools-nodejs/vighnesh153-astro/website/src/components/projects/graphics/grid-path-finder/GridPathFinderRoot.tsx
import { createSignal, For, onMount, Show } from "solid-js";
import { range, sleep } from "@vighnesh153/tools";

import {
  getCellColor,
  GridPathFinderGame,
  GridPathFinderGameManager,
} from "@vighnesh153/tools-browser/graphics_programming";

import { Button } from "@/components/solid/buttons/Button.tsx";

const cellSize = 15;

export function GridPathFinderRoot() {
  let container!: HTMLDivElement;

  const [rows, setRows] = createSignal(0);
  const [cols, setCols] = createSignal(0);
  const [mounted, setMounted] = createSignal(false);
  const [game, setGame] = createSignal<GridPathFinderGame>();
  const [gameManager, setGameManager] = createSignal<
    GridPathFinderGameManager
  >();

  const createNewGame = () => {
    return GridPathFinderGame.createNewWithDefaults(rows(), cols());
  };

  onMount(() => {
    const rect = container.getBoundingClientRect();
    setCols(
      Math.floor((window.innerWidth - rect.left - rect.right) / cellSize - 1),
    );
    setRows(Math.floor((window.innerHeight - rect.top) / cellSize - 10));
    setGame(createNewGame());
    setGameManager(new GridPathFinderGameManager(game()!));
    setMounted(true);
  });

  const solve = () => {
    const frames = gameManager()?.solve();
    if (!frames) {
      return;
    }

    const showNextFrame = () => {
      const nextFrame = frames.next();
      setGame(game);

      if (!nextFrame.done) {
        requestAnimationFrame(async () => {
          await sleep(50);
          showNextFrame();
        });
      }
    };

    showNextFrame();
  };

  const randomize = () => {
    setGame(createNewGame());
    gameManager()?.randomize(game()!);
  };

  return (
    <>
      <div class="flex justify-center gap-2">
        <Button variant="primary" onClick={solve}>Solve</Button>
        <Button onClick={randomize}>Randomize</Button>
      </div>

      <div
        class="mt-6 border box-border border-text"
        ref={container}
        style={`width: ${cellSize * cols() + 2}px`}
      >
        <Show when={mounted() && cols() > 0}>
          <For each={Array.from(range(0, rows() - 1))}>
            {(row) => (
              <div class="w-fit flex justify-center">
                <For each={Array.from(range(0, cols() - 1))}>
                  {(col) => (
                    <div
                      class="border border-secondary shrink-0 box-border"
                      style={`width: ${cellSize}px; height: ${cellSize}px; background: ${
                        getCellColor(game()!, row, col)
                      }`}
                    />
                  )}
                </For>
              </div>
            )}
          </For>
        </Show>
      </div>
    </>
  );
}

// nodejs-tools/nodejs-apps/vighnesh153-astro-svelte/src/components/projects/graphics/grid-path-finder/GridPathFinderRoot.svelte
<script lang="ts">
  import { GridPathFinderGameManager, GridPathFinderGame, getCellColor } from '@vighnesh153/graphics-programming';
  import { range, sleep } from '@vighnesh153/utils';
  import { onMount } from 'svelte';

  import Button from '@/components/Button.svelte';

  const cellSize = 15;

  let rows: number;
  let cols: number;
  let mounted = false;
  let container: HTMLDivElement;
  let game: GridPathFinderGame;
  let gameManager: GridPathFinderGameManager;

  function createNewGame() {
    return GridPathFinderGame.createNewWithDefaults(rows, cols);
  }

  onMount(() => {
    const rect = container.getBoundingClientRect();
    cols = Math.floor(rect.width / cellSize - 1);
    rows = Math.floor((window.innerHeight - rect.top) / cellSize - 10);
    game = createNewGame();
    gameManager = new GridPathFinderGameManager(game);
    mounted = true;
  });

  function solve() {
    const frames = gameManager.solve();

    function showNextFrame() {
      const nextFrame = frames.next();
      game = game;

      if (!nextFrame.done) {
        requestAnimationFrame(async () => {
          await sleep(50);
          showNextFrame();
        });
      }
    }

    showNextFrame();
  }

  function randomize() {
    game = createNewGame();
    gameManager.randomize(game);
  }
</script>

<div class="flex justify-center gap-2">
  <Button variant="primary" on:click={solve}>Solve</Button>
  <Button on:click={randomize}>Randomize</Button>
</div>

<div class="mt-6 border box-border border-text" bind:this={container} style={`width: ${cellSize * cols + 2}px`}>
  {#if mounted}
    {#each range(0, rows - 1) as row}
      <div class="w-fit flex justify-center">
        {#each range(0, cols - 1) as col}
          <div
            class="border border-secondary shrink-0 box-border"
            style={`width: ${cellSize}px; height: ${cellSize}px; background: ${getCellColor(game, row, col)}`}
          />
        {/each}
      </div>
    {/each}
  {/if}
</div>
