// tools-nodejs/vighnesh153-astro/website/src/components/projects/games/pong-game/PongGameRoot.tsx
import { createSignal, onMount } from "solid-js";
import {
  CanvasWrapperImpl,
  PongGame,
} from "@vighnesh153/tools-browser/graphics_programming";

export function PongGameRoot() {
  let canvasElement!: HTMLCanvasElement;
  const [game, setGame] = createSignal<PongGame>();

  const handleMouseMove = (e: MouseEvent) => {
    game()?.handleMouseMove(e, document.documentElement.scrollTop);
  };

  onMount(() => {
    const canvasWrapper = new CanvasWrapperImpl(canvasElement);
    const gameInstance = new PongGame(canvasWrapper);
    const frames = gameInstance.start();
    function showNextFrame() {
      if (!frames.next().done) {
        requestAnimationFrame(showNextFrame);
      }
    }
    showNextFrame();
    setGame(gameInstance);
  });

  return (
    <canvas
      class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text"
      ref={canvasElement}
      onMouseMove={handleMouseMove}
    >
      Sorry your browser doesn't support the canvas element
    </canvas>
  );
}

// tools-nodejs/nodejs-apps/vighnesh153-astro/src/components/projects/games/pong-game/PongGameRoot.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  import { PongGame, CanvasWrapperImpl } from '@vighnesh153/graphics-programming';
  import type { CanvasWrapper } from '@vighnesh153/graphics-programming';

  let canvasElement: HTMLCanvasElement;
  let canvasWrapper: CanvasWrapper;
  let game: PongGame;

  function handleMouseMove(e: MouseEvent) {
    game.handleMouseMove(e, document.documentElement.scrollTop);
  }

  function newGame() {
    if (canvasWrapper) {
      game = new PongGame(canvasWrapper);
      const frames = game.start();
      function showNextFrame() {
        if (!frames.next().done) {
          requestAnimationFrame(showNextFrame);
        }
      }
      showNextFrame();
    }
  }

  onMount(() => {
    canvasWrapper = new CanvasWrapperImpl(canvasElement);
    newGame();
  });
</script>

<canvas
  class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text"
  bind:this={canvasElement}
  on:mousemove={handleMouseMove}
>
  Sorry your browser doesn't support the canvas element
</canvas>
