// tools-nodejs/vighnesh153-astro/src/components/projects/graphics/twinkling-stars/TwinklingStarsRoot.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import {
    TwinklingStarsGame,
    CanvasWrapperImpl,
    type CanvasWrapper,
  } from "@vighnesh153/tools-browser/graphics_programming";

  let canvasElement: HTMLCanvasElement;
  let canvasWrapper: CanvasWrapper;
  let game: TwinklingStarsGame;

  function newGame() {
    if (canvasWrapper) {
      game = new TwinklingStarsGame(canvasWrapper);
      const frames = game.start();
      function showNextFrame() {
        if (!frames.next().done) {
          requestAnimationFrame(showNextFrame);
        }
      }
      showNextFrame();
    }
  }

  onMount(() => {
    canvasWrapper = new CanvasWrapperImpl(canvasElement);
    newGame();
  });
</script>

<canvas
  class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text"
  bind:this={canvasElement}
>
  Sorry your browser doesn't support the canvas element
</canvas>

// tools-nodejs/vighnesh153-astro/website/src/components/projects/graphics/twinkling-stars/TwinklingStarsRoot.tsx
import { onMount } from "solid-js";

import {
  CanvasWrapperImpl,
  TwinklingStarsGame,
} from "@vighnesh153/tools-browser/graphics_programming";

export function TwinklingStarsRoot() {
  let canvasElement!: HTMLCanvasElement;

  onMount(() => {
    const canvasWrapper = new CanvasWrapperImpl(canvasElement);
    const game = new TwinklingStarsGame(canvasWrapper);
    const frames = game.start();
    function showNextFrame() {
      if (!frames.next().done) {
        requestAnimationFrame(showNextFrame);
      }
    }
    showNextFrame();
  });

  return (
    <>
      <canvas
        class="mt-6 mx-auto w-full max-w-3xl aspect-video bg-text"
        ref={canvasElement}
      >
        Sorry your browser doesn't support the canvas element
      </canvas>
    </>
  );
}
