// tools-nodejs/vighnesh153-astro/src/components/projects/tsx-playground/CodePreview.svelte
<script context="module" lang="ts">
  export type CodePreviewResult =
    | {
        status: 'bundling';
      }
    | {
        status: 'success';
        outputCode: string;
      }
    | {
        status: 'error';
        bundleError: string;
      };
</script>

<script lang="ts">
  import { baseIframeHtmlCode } from '@vighnesh153/tsx-bundler';

  export let result: CodePreviewResult = {
    status: 'bundling',
  };

  let previewIframe: HTMLIFrameElement;

  $: (() => {
    if (result.status === 'success' && previewIframe) {
      const outputCode = result.outputCode;
      previewIframe.srcdoc = baseIframeHtmlCode;
      setTimeout(() => {
        previewIframe.contentWindow?.postMessage(outputCode);
      }, 50);
    }
  })();
</script>

<div class="w-full h-full p-4 bg-text">
  {#if result.status === 'bundling'}
    <div class="text-background">Bundling...</div>
  {:else if result.status === 'error'}
    <div class="text-[red] whitespace-pre overflow-x-auto">
      <div class="font-bold text-xl">Some error occurred while bundling</div>
      <div>{result.bundleError}</div>
    </div>
  {:else}
    <iframe
      bind:this={previewIframe}
      class="w-full h-full"
      title="preview"
      sandbox="allow-same-origin allow-scripts"
      srcdoc={baseIframeHtmlCode}
    />
  {/if}
</div>

// nodejs-tools/nodejs-apps/tsx.vighnesh153.com/src/components/CodePreview.tsx
import React, { useEffect, useRef } from 'react';

import { Spinner } from './Spinner';
import { defaultHtml } from '../utils/constants';

export interface CodePreviewProps {
  bundling: boolean;
  bundleError: string;
  outputCode: string;
}

export function CodePreview({ bundling, bundleError, outputCode }: CodePreviewProps): JSX.Element {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const iframeRef = useRef<any>();

  // send the code to iframe
  useEffect(() => {
    if (bundling) return;
    if (bundleError) return;
    if (!iframeRef.current) return;

    // reset the html doc
    iframeRef.current.srcdoc = defaultHtml;

    // send output code as message, to the iframe
    setTimeout(() => {
      iframeRef.current?.contentWindow?.postMessage?.(outputCode);
    }, 50);
  }, [outputCode, bundling, bundleError]);

  if (bundling) {
    return (
      <div style={bundlingStyles}>
        <Spinner />
      </div>
    );
  }

  if (bundleError) {
    return (
      <div style={bundleErrorStyles}>
        <div style={{ fontWeight: 'bold', fontSize: '1.5rem' }}>Some error occurred while bundling</div>
        <span>{bundleError}</span>
      </div>
    );
  }

  return (
    <iframe
      title="preview"
      sandbox="allow-same-origin allow-scripts"
      style={rootStyles}
      ref={iframeRef}
      srcDoc={defaultHtml}
    />
  );
}

const rootStyles: React.CSSProperties = {
  width: '100%',
  borderWidth: 2,
  borderColor: 'initial',
  borderStyle: 'inset',
};

const bundlingStyles: React.CSSProperties = {
  ...rootStyles,
  padding: '1rem',
};

const bundleErrorStyles: React.CSSProperties = {
  ...rootStyles,
  padding: '1rem',
  color: 'red',
  whiteSpace: 'pre',
  overflowX: 'auto',
};
