// tools-nodejs/vighnesh153-astro/website/src/components/Link.tsx
import {
  type AnchorHTMLAttributes,
  type PropsWithChildren,
  type ReactNode,
} from "react";
import { classes } from "@/utils/classes.ts";

import {
  getPrimaryButtonClasses,
  getSecondaryButtonClasses,
} from "./buttons/Button.tsx";

export interface LinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  linkType?: "regular" | "primary-btn" | "secondary-btn";
}

export function Link(
  { linkType = "regular", className, ...props }: PropsWithChildren<
    LinkProps
  >,
): ReactNode {
  if (linkType == "regular") {
    return (
      <a
        {...props}
        className={classes(className, "regular-link")}
      />
    );
  }

  if (linkType == "primary-btn") {
    return (
      <a
        {...props}
        className={classes(className, getPrimaryButtonClasses())}
      />
    );
  }

  if (linkType == "secondary-btn") {
    return (
      <a
        {...props}
        className={classes(className, getSecondaryButtonClasses())}
      />
    );
  }

  return null;
}

// nodejs-tools/nodejs-apps/vighnesh153.dev_astro_svelte/src/components/Link.svelte
<script lang="ts">
  import { classes } from '@/utils';
  import type { HTMLAnchorAttributes } from 'svelte/elements';

  interface $$Props extends HTMLAnchorAttributes {
    linkType?: 'regular' | 'primary-btn' | 'secondary-btn';
  }
  export let linkType: $$Props['linkType'] = 'regular';

  const { class: className, href } = $$props;
</script>

<a {...$$props} {href} class={classes(className, `${linkType}-link`)}>
  <slot />
</a>
