// tools-nodejs/vighnesh153-astro/website/src/components/AuthIndicator.tsx
import { useStore } from "@nanostores/react";

import type { UserInfo } from "@/models/user_info.ts";
import { loggedInUser } from "@/store/auth.ts";
import { initiateLogout } from "@/utils/auth.ts";
import { computeInitialsFromName } from "@/utils/computeInitialsFromName.ts";
import { classes } from "@/utils/classes.ts";
import { GoogleSignInButton } from "./buttons/index.ts";
import { Avatar } from "./Avatar.tsx";
import { Menu, MenuButton, MenuItem, MenuItems } from "@headlessui/react";

export type AuthIndicatorProps = {
  userInfo: UserInfo;
};

export function AuthIndicator() {
  const $loggedInUser = useStore(loggedInUser);

  return (
    <div className="w-[117px]">
      {$loggedInUser !== null
        ? (
          <Menu>
            <MenuButton className="flex gap-3 items-center">
              <div className="shrink-0">
                <Avatar
                  userInitials={computeInitialsFromName($loggedInUser!.name)}
                  imageLink={$loggedInUser!.profilePictureUrl}
                />
              </div>
              <div
                className={classes(
                  `
                    w-20 inline-block
                    grow-0
                    whitespace-nowrap overflow-hidden text-ellipsis
                  `,
                )}
              >
                {$loggedInUser!.name.split(" ")[0]}
              </div>
            </MenuButton>
            <MenuItems>
              <MenuItem>
                <span
                  className={classes(
                    `w-full px-6 py-2 
                    bg-secondary text-text 
                    flex gap-1

                    hover:bg-background hover:text-accent
                    `,
                  )}
                  role="button"
                  onClick={() => initiateLogout()}
                >
                  Log out
                </span>
              </MenuItem>
            </MenuItems>
          </Menu>
        )
        : <GoogleSignInButton />}
    </div>
  );
}

// nodejs-tools/nodejs-apps/vighnesh153-astro/src/components/solid/AuthIndicator.tsx
import { createEffect, createSignal, Show } from 'solid-js';

import { type CompleteUserInfo } from '@vighnesh153/tools';

import { browserCookieReaderFactory, classes, computeInitialsFromName, initiateLogout } from '@/utils/index.ts';
import { GoogleSignInButton } from './buttons/index.ts';
import { Avatar } from './Avatar.tsx';
import { Menu } from './Menu.tsx';
import type { ListItemProps } from './ListItem.tsx';

export type AuthIndicatorProps = {
  userInfo: CompleteUserInfo;
};

export function AuthIndicator() {
  const [shouldDisplay, setShouldDisplay] = createSignal<boolean>(false);
  const [userInfo, setUserInfo] = createSignal<CompleteUserInfo | null>(null);

  const menuItems: ListItemProps[] = [
    {
      text: 'Log out',
      onClick: () => initiateLogout(),
    },
  ];

  // parse user info from cookies
  createEffect(async () => {
    const browserCookieReader = browserCookieReaderFactory();
    setUserInfo(await browserCookieReader.readUserInfo());
    setShouldDisplay(true);
  });

  return (
    <div class="w-[117px]">
      <Show when={shouldDisplay()}>
        <Show when={userInfo() !== null} fallback={<GoogleSignInButton />}>
          <Menu
            placement="bottom-end"
            items={menuItems}
            controlElement={(_, toggle) => (
              <button class="flex gap-3 items-center" onClick={() => toggle()}>
                <div class="shrink-0">
                  <Avatar
                    userInitials={computeInitialsFromName(userInfo()!.name)}
                    imageLink={userInfo()!.profilePictureUrl}
                  />
                </div>
                <div
                  class={classes(
                    `
              w-73 inline-block
              grow-0
              whitespace-nowrap overflow-hidden text-ellipsis
              `
                  )}
                >
                  {userInfo()!.name.split(' ')[0]}
                </div>
              </button>
            )}
          />
        </Show>
      </Show>
    </div>
  );
}
